### ISSUE TITLE
New App Name and Visual Update

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/trackslash-audio-ripper#19]
# Motivation

This issue will rename the page title and h1 to fit the new app name "TrackSlash Audio Ripper". Additionally, rather than a plain white background, the page will include a background image for a more professional look.

# Tasks

- [x] Rename page title and h1
- [x] Add an images folder to the server folder
- [x] Add a background image to the folder and set the source on styles.css
- [x] Change font colors accordingly so that text shows up against new background
