### ISSUE TITLE
User can get feedback if forms are not properly filled out.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/trackslash-audio-ripper#21]
# Motivation

Without clear feedback, users will not know why a submission is not processing, ultimately diminishing user experience.

# Tasks

- [x] Url submission form
    - [x] Update so that it displays an error even for urls missing "https://www.youtube.com/"
    - [x] Clear the error message when it is no longer applicable
- [x] Tracklist forms
   - [x] Create an error message that displays when trying to load timecodes from a description 
        without timecodes
   - [x] Create a regex check so that invalid timecodes cannot be submitted
   - [x] Create an error message that displays which tracks are not conforming to the proper 
           convention
    - [x] Clear the error message when it is no longer applicable
- [x] Timecode submission form
    - [x] Create an error message when the timecode submission form contents do not contain any 
           timecodes
    - [x] Clear the error message when it is no longer applicable

**Comment by danielduffield** [comment]
![screen shot 2017-07-21 at 10 52 15 am](https://user-images.githubusercontent.com/29046343/28475833-b69a524e-6e02-11e7-9c29-77c239d70414.png)
