### ISSUE TITLE
User can see download and slicing progress.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/trackslash-audio-ripper#25]
# Motivation

In order to give more clarity to users about the progress of ongoing operations such as album download and track slicing, users should have a visual indicator of progress that they can monitor to know roughly when operations will completely.

# Tasks

- [x] Install socket.io as a dependency
- [x] Create a websocket event to send download progress from the server to the client
- [x] Display download progress on the page
- [x] Create another websocket event to send progress corresponding to track slicing
- [x] Display track slicing progress on the page
