### ISSUE TITLE
Users can click the title to navigate back to the beginning.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/trackslash-audio-ripper#28]
# Motivation

In order to help users get back to the start more easily, the page title should be a link that takes users back to the URL submit form.

# Tasks

- [x] Wrap the main title in a link to "/#"
- [x] Wrap the subtitle in a link to "/#"
- [x] Add a class for the links to remove text decoration
- [x] Add a hover effect to slightly change the font color to better indicate that the title is clickable.
