### ISSUE TITLE
Deploy to Heroku.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/trackslash-audio-ripper#31]
# Motivation

Users should be able to access the application through Heroku rather than cloning and installing the repository.

# Tasks

- [x] Add to package.json:
    - [x] Create a postinstall script.
    - [x] Add an engines specification.
- [x] Conform to OGP protocol for LinkedIn media sharing:
    - [x] Add appropriate meta scripts to the index.html file.
    - [x] Create an app meta image.
    - [x] Construct an Express route to serve the meta image.
- [x] Bug fix:
    - [x] Fix the display width issue causing horizontal scrollbar to appear.
- [x] Refactor:
    - [x] Replace the onClick button for URL submissions with an onSubmit handler.
