### ISSUE TITLE
Refactor the download queue to impose time limits on file storage.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/trackslash-audio-ripper#34]
# Motivation

Refactoring the download queue should be completed in order to prepare for application  deployment to Heroku.

# Tasks

- [x] Handle downloaded files on server startup:
    - [x] Add a check on server load to scan downloaded files and delete files conditionally based on 
        birthtime.
    - [x] Build an existing queue using non-expired files based on a created timeLimit.
- [x] Handle downloaded files periodically:
    - [x] Create a function that scans the queue for expired files based on expiration timestamp.
    - [x] Delete expired files and return an updated queue.
- [x] Refactor downloaded file structure:
    - [x] Place sliced tracks in "unique" folder within tracks folder based on user socketId.
    - [x] Place zipped tracklist files in socketId named folder in zip folder of YoutubeId folder.
