### ISSUE TITLE
User can see a loading reticle during the track slicing phase.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/trackslash-audio-ripper#37]
# Motivation

Track slicing status should provide users with greater indication of work in progress, with a rotating download icon.

# Tasks

- [x] Import the Font Awesome stylesheet for use of icons.
- [x] Replace download icons with appropriate Font Awesome icon.
- [x] Add a default text to the download progress indicator.
- [x] Add to the rotating download icon next to the track slice progress.
