### ISSUE TITLE
Bug fix: Track slicing operations following tracklist POST requests cause request timeout.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/trackslash-audio-ripper#38]
# Motivation

Submitting tracklists with a lot of tracks will cause the request to timeout while tracks are being sliced. This can be fixed by changing the structure of the tracklist POST request handling and leveraging Socket.io for track slice progress.

# Tasks

- [x] Change tracklist POST request response to be approved if the submission is valid, before tracklist slicing takes place.
- [x] Create a websocket event that is triggered by tracklist POST requests and emits track slice progress.
- [x] Prevent the client from changing view after receiving 202 response from POST request.
- [x] Send the compressed album zip path with track slice and compression completion.
- [x] Update client view upon completion of websocket event.
