### ISSUE TITLE
Implement demo app limitations to conform with Heroku guidelines.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/trackslash-audio-ripper#40]
# Motivations

To conform with Heroku guidelines, file download will be disabled in a demo version of the app, rerouting to a page where tracks can be played within the browser but not downloaded.

# Tasks

- [x] Create a component that allows users to play tracks in the browser.
- [x] Disable track download links and set href to empty.
- [x] Highlight currently playing tracks and display name of track above audio player.
