### ISSUE TITLE
Users can set track playback to continuous for auto play of the tracklist.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/trackslash-audio-ripper#47]
# Motivation

Users should have the option to play tracks continuously on the final tracklist page.

# Tasks

- [x] Use a Font Awesome icon for the continuous play button.
- [x] Attach an event listener to toggle continuous play on click.
- [x] Update the selected track upon transition to next track if continuous play is enabled.
- [x] Update the now playing text upon track transition.
