### ISSUE TITLE
Users can shuffle playback on the final tracklist.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/trackslash-audio-ripper#48]
# Motivation

Users should be able to toggle shuffle on the audio controls to listen to the playlist tracks at random.

# Tasks
- [x] Create a shuffle button with a Font Awesome icon.
- [x] Add to the audio controls listener to allow toggling of shuffle setting, which plays tracks in a randomized playlist starting with the currently playing track.
- [x] Create an Audio Module smart component:
    - [x] Construct using the $audioPlayer, tracklist, and path.
    - [x] Add methods for shuffling the tracklist, toggling settings, and selecting a new track.
    - [x] Replace old logic to save audio player state within component.
- [x] Update the track selection render to account for Audio Module refactor.
