### ISSUE TITLE
Users can skip backward or forward in current tracklist.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/trackslash-audio-ripper#50]
# Motivation

Users should have the option of skipping forward or backward using buttons on the audio control panel.

# Tasks
- [x] Create buttons corresponding to skip forward and backward.
- [x] Use Font Awesome icons for visual clarity and consistency.
- [x] Attach an event listener to skip buttons that triggers the Audio Module skipTrack method forward or backward depending on the target.
